\o dbschema.txt

\d acc_trans      
\d address        
\d addressid      
\d ap             
\d ar             
\d assembly       
\d assemblyid     
\d audittrail     
\d bank           
\d br             
\d business       
\d cargo          
\d chart          
\d contact        
\d contactid      
\d curr           
\d customer       
\d customertax    
\d defaults       
\d department     
\d dpt_trans      
\d employee       
\d exchangerate   
\d gifi           
\d gl             
\d id             
\d inventory      
\d inventoryid    
\d invoice        
\d invoiceid      
\d jcitems        
\d jcitemsid      
\d language       
\d makemodel      
\d oe             
\d orderitems     
\d orderitemsid   
\d parts          
\d partscustomer  
\d partsgroup     
\d partstax       
\d partsvendor    
\d payment        
\d paymentmethod  
\d pricegroup     
\d project        
\d recurring      
\d recurringemail 
\d recurringprint 
\d semaphore      
\d shipto         
\d sic            
\d status         
\d tax            
\d translation    
\d trf            
\d vendor         
\d vendortax      
\d vr             
\d warehouse      
\d yearend        

